spring:
  freemarker:
    cache: false
  datasource:
    url: jdbc:mysql://172.17.137.100/csc-sys?useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**
  data:
    elasticsearch:
      properties:
        path:
          name: target/elastic
        transport:
          tcp:
            connect_timeout: 120s
banner:
  location: banner.txt

server.port: 8011
server.reload: automatic

appprops:
  host: http://csc.flyme.cn/