site:
  name: 核心系统社区 CoreSys Community
  baseUrl: http://csc.flyme.cn/
  sessionName: _user
  adminSessionName: _admin_user
  cookieName: _token
  adminCookieName: _admin_token
  cookieDomain: csc.flyme.cn
  cookieExpireTime: 30 # 单位天
  pageSize: 20
  avatarPath: /data/csc-sys/resources/static/images/avatar/
  uploadPath: /data/csc-sys/resources/static/images/upload/
  sections:
    - 分享
    - 问答
    - 新闻
    - 博客
    - 管理通告
    - 管理通告-非公开回复
  theme: bootstrap
  beforeUrl: beforeUrl
  elastic: false # true 开启 false 关闭
  adminRoleId: 1
  replyPrivateSection: 管理通告-非公开回复