site:
  name: 核心系统社区
  baseUrl: http://localhost
  sessionName: _user
  adminSessionName: _admin_user
  cookieName: _token
  adminCookieName: _admin_token
  cookieDomain: localhost
  cookieExpireTime: 30 # 单位天
  pageSize: 20
  avatarPath: C:/Users/gangjian@meizu.com/Documents/GitHub/csportal/src/main/resources/static/images/avatar/
  uploadPath: C:/Users/gangjian@meizu.com/Documents/GitHub/csportal/src/main/resources/static/images/upload/
  sections:
    - 分享
    - 问答
    - 新闻
    - 博客
    - 管理通告
    - 管理通告-非公开回复
  theme: bootstrap
  beforeUrl: beforeUrl
  elastic: true # true 开启 false 关闭